app:
  env : ${ENV:dev}
  topics:
    file-metadata-updates: file_metadata_updates

management:
    endpoints:
        web:
        exposure:
            include: health,metrics,prometheus


spring:
  application:
    name: file-metadata-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
          audiences: file-metadata-service
          public-key-location: application.yaml


  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: file_metadata_service
    local-datacenter: datacenter1
    schema-action : NONE

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5s

  kafka:
    bootstrap-servers: localhost:9092

    admin:
      auto-create: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        enable.idempotence: true

    consumer:
      group-id: file_metadata_service_group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        max.poll.records: 100
        session.timeout.ms: 15000
        heartbeat.interval.ms: 5000
    listener:
      missing-topics-fatal: false
  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.cassandra: INFO
    org.springframework.kafka: INFO
  include-application-group: